### ISSUE TITLE
Error 500 - PASSWORD_ARGON2I not defined

### ISSUE THREAD

**Issue by drfraser** [mkucej/i-librarian-free#10]
Hi,

I decided to upgrade to version 5.1 - am using a Mac with nginx and php74-fpm (I could write up the process if you want), but then ran into another issue.

According to the PHP documentation, PASSWORD_ARGON2I is only defined if PHP has been compiled with Argon2 support, which doesn't seem to be standard especially when one uses pre-built binaries (I am using macports). I didn't want to change the code and certainly not compile a custom version of PHP (which didn't seem right) so ... I finally tracked down a solution.

Sodium defines this constant and has support for Argon2. So I installed the php74-sodium extension and things work. So it ought to be in the list of mentioned extensions to install or enable

**Comment by mkucej** [comment]
I think this was not caught, because Sodium comes bundled in PHP on Ubuntu. I am wondering, if `Administrator > Software details` gave you an indication that Sodium is missing.

> I could write up the process if you want

If you think you could help other Mac users with simpler instructions, we will include it in the README. Our current Mac instructions are old and very complicated. Thanks.

**Comment by drfraser** [comment]
When I got things working, I was presented with a page that offered a choice between migration and setting up a new user. I chose the 'new user' route because I wanted to make everything worked properly (lot of hassle getting php-fpm and nginx to work). But the ability to use Argon2 as the encryption method was not there, so setting up the initial new user failed. And I could not reach the administrator screen because I could not get the system to set itself up to that point - immediate 500 error in a red box....

So I would say there needs to be a check on that initial screen that Sodium or support for Argon2 is already present. Or show a warning and indicate the usual bcrypt will be used instead... Sodium may be mostly standard, but it would have been nice to know that ahead of time (I never heard of any of this before, haven't done any PHP work for years)

After migrating my old installation, everything is working great. The new look is pretty nice, but I sort of miss the old look :)

Sure, I can write something up, or at least validate the current instructions. I am on OS X 10.11 but that *shouldn't* be a real issue for anyone doing a stock install on 10.12+.  I will also write up how to configure nginx and fastcgi / php-fpm.

**Comment by mkucej** [comment]
Of course, one can't get to the Admin menu without an account. /facepalm

> I will also write up how to configure nginx and fastcgi / php-fpm.

That sounds even more complicated than current instructions. Mac used to be much easier for PHP apps, sigh.

**Comment by drfraser** [comment]
Hi, I am almost done with writing up the updated Linux/Mac instructions, but there is an issue. If a person uses Macports, Homebrew or MAMP to setup a web server and PHP, dealing with Sodium/the ARGON2 encryption and extensions should not be a problem. 

But the OSX-LIIP package your original instructions reference is actually a pre-built binary that does not include the argon2 or sodium modules - and there is no good way to piggyback off that osx-liip process because you'd have to modify it as well and build PHP yourself - or use "my" custom version which I do not want to deal with supporting for people. Getting the LIIP PHP to work with an external made-somewhere-else libsodium extension... I can foresee issues arising.

So it looks like the best idea, I think, is to remove the instructions about installing PHP and trying to use OS X's built in Apache and instead encourage people to use brew etc. People who do want that setup will have to be able to build php from scratch and so don't really need any instructions.

This all depends on how much you want iLibrarian to ensure the use of ARGON2 over the built in default. I actually just made a patch to encryption.php to not break if ARGON2 is not supported but you are the program/product manager here.  So let me know and I will tidy up the instructions or toss my patch.

**Comment by drfraser** [comment]
Oh wait, sorry... there is a PECL extension of Sodium that could be installed. I will test that option.

**Comment by mkucej** [comment]
The SaaS is using Argon, which is the most robust hashing option available in PHP 7.2. We would prefer if Free database is 100% compatible with the SaaS. For this reason, I agree that we can **remove the liip.ch** instructions.

**Comment by mkucej** [comment]
> The new look is pretty nice, but I sort of miss the old look :)

I meant to ask you what it is from the old look that you miss?

**Comment by drfraser** [comment]
Half of it is just learning a new interface, but I realize now the summary info view was missing information I expected to see - it is too 'blank'. Other missing functionality I used a lot - 

the list of quick operations like 'Categories' or 'Journals' on the always present sidebar in 4.10.  

And the tags screen when looking at a specific PDF - the old screen was a nice ordered table like list. The new screen is a random pile (I have lots of tags) so it is more difficult to scan through it. (random idea: an option to turn that into a "word cloud")

And having a list of the titles in the current search results in the sidebar on the left (when examining a specific item) was useful. All of this may really be related to how I work, of course.

But the interface is cleaner and there is more of a sense of being less 'clumsy' in that buttons are not in unusual spots / there is more of a standardized look to things.

**Comment by mkucej** [comment]
Thank you for the feedback.
