### ISSUE TITLE
Hide items from Library if assigned to Restricted Project

### ISSUE THREAD

**Issue by robbaker292** [mkucej/i-librarian-free#101]
We have a number of projects that various members of the team can and cannot have access to and we can assign documents to those projects, and this feature works well.

However, all uploaded documents are visible to all users. The very nature of the titles of these documents gives clues as to what areas of work some teams are doing.

Is there an option to hide documents from the main Library if a user does not have access to the projects those documents have been assigned to?

**Comment by mkucej** [comment]
There is no way to have private documents in *I, Librarian*. Project access restriction is just for your convenience, it's not a security feature.
