### ISSUE TITLE
I, librarian is unable to backup library

### ISSUE THREAD

**Issue by mnokturnal** [mkucej/i-librarian-free#103]
I am trying to backup pdf library from older software I, Librarian 4.10 running on Apache2 and php7.2 on Ubuntu 18.04

I tried to backup library to file /usr/share/i-librarian/www/zaloha

When I click on backup button, I librarian is busy for few seconds and then it writes "Copying files complete". But there is nothing in a folder /usr/share/i-librarian/www/zaloha/library

In apache2 error log

`[Sun Oct 06 09:27:32.353940 2024] [mpm_prefork:notice] [pid 3842] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Oct 06 09:27:32.354008 2024] [core:notice] [pid 3842] AH00094: Command line: '/usr/sbin/apache2'
[Sun Oct 06 09:27:59.681598 2024] [php7:notice] [pid 3844] [client 192.168.1.100:50984] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:03.156597 2024] [php7:notice] [pid 3844] [client 192.168.1.100:50984] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:04.706235 2024] [php7:notice] [pid 3844] [client 192.168.1.100:50984] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:15.965174 2024] [php7:notice] [pid 3846] [client 192.168.1.100:37096] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:17.361975 2024] [php7:notice] [pid 3846] [client 192.168.1.100:37096] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:22.073911 2024] [php7:notice] [pid 3846] [client 192.168.1.100:37096] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
[Sun Oct 06 09:28:25.538341 2024] [php7:notice] [pid 3846] [client 192.168.1.100:37096] PHP Notice:  Undefined variable: hosted in /usr/share/i-librarian/www/jqueryFileTree.php on line 6, referer: http://192.168.1.95/librarian/index2.php
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/discussions.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/fulltext.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/history.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/library.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/nothing': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/database/users.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfcache/00082.pdf.sq3': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00159.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00160.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00161.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00122.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00149.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00150.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00151.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00152.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00153.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00154.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00155.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00156.pdf': No such file or directory
cp: cannot create regular file '/usr/share/i-librarian/www/zaloha/library/pdfs/0/0/00157.pdf': No such file or directory
`

I changed directory permisions /usr/share/i-librarian/www/zaloha 777.
Does not help.

I tried to use another directory for backup. Did not help.

Do you have any ideas how to backup my old I, librarian library ?

**Comment by mkucej** [comment]
I would use whatever backup software is available on your Ubuntu, or just `rsync`.
