### ISSUE TITLE
Error 500 when re-extracting text from all PDFs

### ISSUE THREAD

**Issue by drfraser** [mkucej/i-librarian-free#13]
Not sure if I should have actually done this - was poking around my new installation and vaguely (mis)remembered some mention of a step after migrating the data from version 4.10. So I pressed the Red Buttons with Warnings....

I do not remember getting an explicit instruction to do X otherwise I would have immediately. 

Rebuild Indexes worked fine, but Re-extract all PDFs ran for a bit then a 500 error box showed up with no real info in it. I looked in the PHP error log and this looks like the relevant log entry:

""Internal Error: xref num 2709 not found but needed, try to reconstruct<0a>""

Now I am wondering if I ought to redo the install and re-migrate?  Wait, it might have been a PHP timeout error...  No, it isn't or I have not increased the right setting enough (a setting I do not know about...) The logs say "gateway timeout" but I can't get PHP to give me any real debugging info on the error.

**Comment by mkucej** [comment]
> I do not remember getting an explicit instruction to do X otherwise I would have immediately.

Github releases have a short paragraph on how to upgrade from 4.10, which instructs to re-extract PDFs, otherwise they are not actually searchable.

> Re-extract all PDFs ran for a bit then a 500 error box showed up with no real info in it.

You can set `debug` level of error_messages in your ilibrarian.ini to get the file and line where the error occurred.

> `Internal Error: xref num 2709 not found but needed, try to reconstruct`

That looks like a broken PDF file. You can query `ind_items` table for rows with no full text.

> Now I am wondering if I ought to redo the install and re-migrate?

No need. You can repeat the process of re-extracting after you find out what the error is.

> Wait, it might have been a PHP timeout error. The logs say "gateway timeout"

The script is set to run for 24 hours, but your server returned the timeout error.

**Comment by drfraser** [comment]
> You can set debug level of error_messages in your ilibrarian.ini to get the file and line where the error occurred.

I did try that but did not get any useful information like a stack trace. I will fiddle with things to see if I can get more info and triple check the PHP-FPM settings.

Yeah, some of my PDFs are surely broken / badly made / etc. and I also have added PDF printouts of web pages and slide handouts as well. So some of them may be an issue

**Comment by drfraser** [comment]
well, that was fun... the problem was a fastcgi setting I never had to deal with before (see updated instructions). The PHP FastCGI process was actually still processing PDF files, it was just that Nginx and FPM decided to stop talking and the front end threw an error.... But no real error messages like I was expecting (e.g. PHP ones) and what was there was sparse...
