### ISSUE TITLE
Wrong publication date in item details

### ISSUE THREAD

**Issue by gkaf89** [mkucej/i-librarian-free#17]
In the 'Item summary' page, the publication day seems to always be one day before the date entered in the item details. For instance:

- Item summary: https://drive.google.com/open?id=1acHaff1miPXDk1lvdWpiUKpuOJJe7dDR
- Editing entry details: https://drive.google.com/open?id=1hZ7UagBYq2JKGy5I7IgHSATugpAS4RZ4

**Comment by mkucej** [comment]
Good catch, thank you!
