### ISSUE TITLE
Not possible to copy text from pdf?

### ISSUE THREAD

**Issue by TheNomad11** [mkucej/i-librarian-free#18]
I really like the new version, but I have not found a way to copy text from a pdf while using the ilibrairian pdf viewer. Is this not possible (yet)?

**Comment by addy90** [comment]
I have that "A" symbol to copy text with the i-librarian pdf viewer. Worked for me. Maybe the PDF has to be full text indexed before?

**Comment by TheNomad11** [comment]
aha ok, you're right, it works, thanks!
