### ISSUE TITLE
Add author list in the title and summary view

### ISSUE THREAD

**Issue by mkucej** [mkucej/i-librarian-free#2]
### Pros
* adds useful information

### Cons
* clutters UI space

References pull request #1.

**Comment by grisuthedragon** [comment]
I do not think that it cutters the UI space too much. I made some tests on my desktop and my mobile and it think this looks good. Even colleagues do not complain. 

On my desktop:
![ilibrarian_desktop](https://user-images.githubusercontent.com/912463/79953863-d4d8a380-847c-11ea-9f56-942ddc2fc55a.png)

On my mobile:
![ilibrarian_mobile](https://user-images.githubusercontent.com/912463/79953909-e15cfc00-847c-11ea-823c-59c7a04317a1.png)

As long as it is align with the title and does not disturb the "PDF-Download" column, this should be fine.
