### ISSUE TITLE
Bug when arXiv is entered, after saving twice, it vanishes.

### ISSUE THREAD

**Issue by addy90** [mkucej/i-librarian-free#20]
##### Old text
I would like to request an enhancement:
We have different options to import new items. There we can import data by DOI, BibTex, PDF and so on...
After we imported the PDF, we can Edit the item by hand, but we can not rescan by DOI, Arxiv, BibTex and so on.

I think it would be great if it is possible to trigger a rescan. For example if you have found a DOI later after importing manually, you want to reimport the official, new data, but you cannot do this without creating a duplicate. Or if you found an official BibTex, you want to merge that data, but also can only create a new duplicate. I know that it is possible to merge duplicates, but this is a blind operation where you don't know which version is imported.

I suggest that it should be possible to reimport an item and then have a comparison view of the data where you can select the version you want to import at every field (for example take author on the right but abstract from the left) and/or manually edit that version, before you save. A side-by-side view of the current version and the data that one got by rescan/reimport would make this possible.

**Comment by addy90** [comment]
I just found the Auto-Update field after hours... this is what I was searching, but I did not see it before.
Problem was, when I have an arXiv entered, there is an additional arXiv entry that is empty and when I save twice, the arXiv that was entered before vanishes. So I did not see the autoupdate function before.

Maybe we have a bug here and not an enhancement!

**Comment by mkucej** [comment]
Thank you for reporting this. Users can inadvertently delete their Arxiv IDs, and it is very annoying to recover them. UID type should not be pre-selected to any value in the Edit form.
