### ISSUE TITLE
Custom autogenerated bibtex id preserves commas (for example from title)

### ISSUE THREAD

**Issue by addy90** [mkucej/i-librarian-free#21]
The bibtex id default custom format includes the title (which is nice for referencing the right document later), but unfortunately, I had a title with a comma within the beginning, for example see the following random title `Bla, this is a great title`.

Spaces are removed, but not the comma, see \
https://github.com/mkucej/i-librarian-free/blob/master/classes/media/scalarutils.php#L370

The resulting bibtex then has something similar to `@article{Author-2020-Bla,thisisagreattitle,`
So the comma from the title is end-of-line symbol in bibtex format and clashes with the comma at the end of the line. Somehow I could refer to it with `Author-2020-Bla` but this is misleading because the rest is missing in the cite reference.

Maybe other symbols should not be present within the bibtex citation key, too? I did not find a clear solution on this unfortunately.

**Comment by mkucej** [comment]
We can remove everything that's not a UTF-8 letter, number, or a separator &mdash; `/[^\p{L}\p{N}-_]/u`. Would that work for you?

**Comment by addy90** [comment]
This sounds good, should create citation keys that work in every case!
I would really appreciate this!

**Comment by addy90** [comment]
I have seen your commit @mkucej but I think this is not right.
The $format consists of `-` or `_` or `[:space:]`

![grafik](https://user-images.githubusercontent.com/6824664/81738087-64c8a680-9499-11ea-9382-b3d5f4fcf543.png)

The place you replace the characters with the mentioned regex will frickle the original $format delimiters.

Maybe you should preg_replace inside the switch case before appending to $output, except when using the delimiter columns case.

**Comment by mkucej** [comment]
I think it is a correct fix. The expression `/[^\p{L}\p{N}\-_]/u` will remove every character, except those in the brackets, which are letters, numbers, minus, and underscore. As far as I know, space is not an allowed delimiter, only the `-`, `_` and no delimiter options are provided. Are you getting mangled Bibtex IDs?

**Comment by addy90** [comment]
Ah, no, you are right, it replaces everything except these characters. My mistake, did not read it right.
I did not try out your fix yet, just made somthing up after a hard working day... 😄 please forget it and thank you for your quick reaction!

**Comment by addy90** [comment]
Works very well so far, thank you a lot! Described situations do not occur anymore and the right characters are replaced.
