### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Niemand112233** [mkucej/i-librarian-free#22]
Hi,
when I install the .deb with dpkg -i then it will tells me that there are some packets missing (e.g. apache2). I installed them with apt-get -f install.
But when I try to access the web GUI I get this error:
"Can't locate required I, Librarian files. Please edit the paths.php file."
But for me everything looks correct in the paths.php file.
What's wrong?

**Comment by addy90** [comment]
Did you create your configuration here?
`/etc/i-librarian/config/ilibrarian.ini`

You can copy from `/etc/i-librarian/ilibrarian-default.ini`.
Please be careful to put the new config in a new subfolder `config` under `/etc/i-librarian`.

**Comment by mkucej** [comment]
This must be a bug in the deb package. The deb should "just work"&trade;. Let me look at that.

**Comment by addy90** [comment]
@mkucej 
You added the `config` path here: https://github.com/mkucej/i-librarian-free/commit/55bf266274db544ae498d7fc93bc5c80fb055210
But paths.php does point to `/etc/i-librarian`.
Maybe at some other place within the deb package configuration, the config path is not set right? I did not look further into this, but had the same problem and found the solution in the index.php code.

**Comment by mkucej** [comment]
OK, @addy90 pointed to the problem. The deb package should be placing the ini file in a `config` subfolder. I will compile a new deb ASAP. You can just move the `/etc/i-librarian/ilibrarian-default.ini` into `/etc/i-librarian/config/ilibrarian-default.ini`.

**Comment by mkucej** [comment]
Fixed deb package uploaded. Thanks for reporting this.
