### ISSUE TITLE
script.min.js missing in 5.2.3 deb package

### ISSUE THREAD

**Issue by addy90** [mkucej/i-librarian-free#23]
Hi, unfortunately in 5.2.3 deb package, instead of `script.min.js` there is `script.js` in `public/js` folder.
This leads to the software not working as it expects `script.min.js`,
see: [classes/mvc/textview.php#L412](https://github.com/mkucej/i-librarian-free/blob/master/classes/mvc/textview.php#L412).

The error is a blank textview not showing anything. Console in Browser shows that `script.min.js` could not be loaded.

```
# ls /usr/share/i-librarian/public/js/
citeproc  plugins.js  script.js  tinymce
```

Luckily, renaming deployed `script.js` to `script.min.js` works and the system loads again.

I did an upgrade from 5.2.2 deb package straight to 5.2.3 package with `dpkg -i`.

Please also see the following log output of terminal:
```
## extracting both deb files to folders 522 and 523 respectively
# dpkg -x i-librarian_5.2.2_all.deb 522
# dpkg -x i-librarian_5.2.3_all.deb 523

## show content of public/js folder from both extracts in comparison
# ls 522/usr/share/i-librarian/public/js/
citeproc  plugins.js  script.min.js  tinymce

# ls 523/usr/share/i-librarian/public/js/
citeproc  plugins.js  script.js  tinymce
```

As you can see, `script.min.js` is definitely missing in 5.2.3 archive, but expected to exist from software in [classes/mvc/textview.php#L412](https://github.com/mkucej/i-librarian-free/blob/master/classes/mvc/textview.php#L412).

**Comment by mkucej** [comment]
Thanks for reporting this. Re-compiled packages uploaded.
