### ISSUE TITLE
Missing required fields in bibtex export

### ISSUE THREAD

**Issue by addy90** [mkucej/i-librarian-free#24]
I am currently having several warnings in my bibtex exports, for example `Warning--empty booktitle` when having `@inproceedings` type.

The problem is not that the booktitle is not set in my case (using chapter reference type), but that it is not exported.
Concerning official documentation: http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf
For example see at 2.1.1 `@inproceedings` type, required fields contains booktitle.
In: https://github.com/mkucej/i-librarian-free/blob/master/classes/export/bibtex.php
It looks like booktitle is not exported for `@inproceedings` but only for conference and chapter, but chapter is no bibtex type, but a reference type in items.

This was only an example. I suggest that the existing Bibtex types in I-Librarian are checked against official documentation and the missing fields are included.

I think this is similar to #8 but it is not the same request.

I am not sure but the missing required fields feel more like a bug, missing optional fields or missing types more like an enhancement. At least the available fields (even when optional) from I-Librarian should be exported correctly when exporting bibtex. I did not check all types against each other, but this should be done just to be sure that this example given is not the only mismatch between given information and exported.

Thank you a lot!

**Comment by mkucej** [comment]
Import/export fixes required to include booktitle, institution, school, holder, etc... in some of the Bibtex types.

**Comment by addy90** [comment]
Thank you a lot, I tried it today and exported all my references again with the new 5.3.0 version.
All missing fields are there and I get no more errors when compiling my bibtex file.
