### ISSUE TITLE
Handling new lines from textareas

### ISSUE THREAD

**Issue by bouffa** [mkucej/i-librarian-free#25]
When a textarea is submitted to a php script, new lines are always mapped to `\n` character.
However, in I,Librarian source code, `PHP_EOL` is used to split the text. `PHP_EOL`  is the platform dependant new line character. If the I, Librarian instance is run on a Windows machine, `PHP_EOL = \r\n`, which breaks correct handling of multiple lines text areas.

Thank you!

**Comment by mkucej** [comment]
Thanks for your report.
