### ISSUE TITLE
Fresh installation of 5.2.3 reports sodium missing

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#26]
I have got a fresh installation of 5.2.3 and when I browse to the http://127.0.0/librarian I see a red text that libsodium is missing.

```
./php -i | grep "sodium"
sodium
sodium support => enabled
sodium compiled version => 2.0.22
libsodium headers version => 1.0.18
libsodium library version => 1.0.18
```
I am not sure what is happening.

**Comment by mkucej** [comment]
PHP must be compiled with PASSWORD_ARGON2I constant enabled.
