### ISSUE TITLE
Fresh installation of 5.2.3 shows SQL errors when first browsed

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#27]
When browsing to the newly manual installed Librarian I get a lot of errors in the SQL, presumably because the database and such is not available yet in the data folder.

Eventually, these errors disappear and I am greeted with an upgrade/create page.

**Comment by mkucej** [comment]
I can't help with this, because I can't reproduce this.

**Comment by schonhose** [comment]
This is the direct results of Red Hat not allowing me to update everything to latest versions. It works well with the WAMP server.
