### ISSUE TITLE
Migration of old database (4.x) not working

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#28]
When performing an upgrade after providing the full path of the library I am greeted with the following error:

```
500 Internal Server Error
Database error: SQLSTATE[HY000]: General error: 1 no such table: primary_titles.
```
Nothing seems to be happening as the PDF folder in data remains empty. Pressing the upgrade button again shows the following:

```
Info
Cannot upgrade, because the database already contains data.
```

Please advise necessary actions for migrating the database.

**Comment by schonhose** [comment]
I just checked that I was running 4.10 as the latest version. Library still works with that version, but I would like to migrate to 5.x

**Comment by mkucej** [comment]
I can't help here, as I cannot reproduce these problems. In general, if you see the `Cannot upgrade, because the database already contains data.` message and you want to attempt the migration again, you can delete the contents of the `data/database` directory, reload, and try again.

**Comment by schonhose** [comment]
This problem occurs when certain PHP extensions are not available, as this is the case with Red Hat linux. I can confirm it works nicely with the provided WAMP server.
