### ISSUE TITLE
Bulk Import

### ISSUE THREAD

**Issue by ark-** [mkucej/i-librarian-free#30]
Excellent project guys. Really like that you offer a free to use version.

It would be great if I could point this at a directory of PDFs and it would import them automatically. I note there is a `data/import` folder but putting PDFs in there doesn't do anything.

Having to manually upload each one is very time consuming.

**Comment by mkucej** [comment]
Have you tried `Import` > `Import Wizard` > `Published PDFs containing a DOI`? You can upload many PDFs from a browser client.

**Comment by ark-** [comment]
> Have you tried `Import` > `Import Wizard` > `Published PDFs containing a DOI`? You can upload many PDFs from a browser client.

Interesting, thanks for the info. I'll give it a shot.

**Comment by ark-** [comment]
For others who may find this issue further down the line. This does work. Thanks for the solution.

Not totally clear from the UI that this is how you bulk import. I wasn't sure what `DOI` meant and so avoided that option.

**Comment by mkucej** [comment]
Yes, import UI section should be improved.
