### ISSUE TITLE
Behavior of author search 

### ISSUE THREAD

**Issue by gapost** [mkucej/i-librarian-free#31]
When I search for an author (either with simple or advanced search) giving only the last name I get no results. However if I add a comma or * after the name it works.

Example: 
I have 1 record with author "A Fert" and 2 records with "A. Fert" 
Searching gives the following results:
1. Search for "Fert": 0 Results
2. Search for "Fert," or "Fert*": 3 results
3. Search for "Fert, A": 3 results + all "a" characters everywhere on the results page are highlighted
4. Search for "Fert, A.": 2 results

I think that the behavior in case 1. is counter-intuitive and should be changed. When I search for the last name I would normally expect to see results. The search for "Fert" should produce all 3 results in the above case.

Searching for last name + initial(s) could be implemented in various ways but it is less common and has difficulties due to the different styles in various bibliographic engines (e.g. "SL", "S.L." or "S. L.") . Thus I don't discuss it here.

**Comment by mkucej** [comment]
Thank you for your report. This was never intended. It's a bug, sorry. It will be fixed in the next version.
