### ISSUE TITLE
Windows stand-alone server looks for missing apache.conf

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#32]
When starting the server using the Windows stand-alone server, Apache looks for "C:\I, Librarian\config\apache.conf" as directed by the last line in `httpd.conf`.

This file does not exist by default but is part of the manual steps. Is it possible to add this information to the readme, allowing users to create the apache.conf using the template used for manual installation?

**Comment by mkucej** [comment]
The installer is supposed to take care of the `config/apache.conf` file installation. A fixed installer was compiled and reuploaded:
https://github.com/mkucej/i-librarian-free/releases/tag/5.4.0
