### ISSUE TITLE
500 server error when deleting item with bad/no PDF

### ISSUE THREAD

**Issue by drfraser** [mkucej/i-librarian-free#33]
I had a PDF file that was not imported because it was a bad file for some reason. So I tried deleting the item to start over.  Instead I got the red error dialog etc:

Return value of Librarian\Media\Pdf::pageCount() must be of the type int, null returned in .../opt/local/var/www/library/classes/media/pdf.php on line 312.

Perhaps this isn't the best solution, but I tweaked the code in pdf.php to return a 0 if the page_count is null - the function signature (return only 'int') was causing the error.  I have made a pull request if you want to use the code. Looking at where pageCount() is called reveals nothing should break (I think) with this change. No idea under what conditions a valid PDF might return a pageCount of null (versus 0).

A check that there are no issues with the PDF in the _delete function might be better... but apparently there was a valid pdf_obj, so no idea what the larger issues might be.

I suppose I could have re-uploaded a fixed PDF instead of deleting the item altogether, but that was not the immediately logical thing to do.

**Comment by mkucej** [comment]
Thank you. I will look at this problem ASAP.
