### ISSUE TITLE
Move PDFs from import folder instead of copying

### ISSUE THREAD

**Issue by wildthyme** [mkucej/i-librarian-free#36]
Having a large PDF library already, the most practical way for me to import them into i-librarian would be via bibtex with filepaths referenced. But from experimentation, it seems the process makes a whole new copy of every file. This requires a lot of unnecessary disk I/O that i can’t conscience. Why not just move the file directly from the `data/imports` to `data/pdfs/…`? Or at least have an option for it.

**Comment by mkucej** [comment]
I agree, moving the files is more appropriate for this action.
