### ISSUE TITLE
error after notes saving

### ISSUE THREAD

**Issue by przemkulas** [mkucej/i-librarian-free#39]
After saving the notes for record, the following error apear: 500 Internal Server Error
E_DEPRECATED: Array and string offset access syntax with curly braces is deprecated

**Comment by mkucej** [comment]
I can't reproduce this. Can you tell me the PHP version and what steps you are taking to trigger this error? Curly braces are not used for offsets anywhere in the code. Is it a specific text of the note that could trigger this?

**Comment by przemkulas** [comment]
I, Librarian 5.5.0
PHP (7.2.0 required) 7.4.4
SQLite (3.22.0 required) 3.31.1

In PHP extensions I have two missing (except ldap) sysvsem, sysvshm.

The error is after saving the note editing box. Does not matter the type of note I try to input, link, plain text or image. The error is the same.

**Comment by mkucej** [comment]
Thank you very much for your report. The issue is caused by the HtmlPurifier external library (http://htmlpurifier.org/). Their newest version does not suffer from this problem. We will upgrade to their newest version in 5.6.0.
