### ISSUE TITLE
Question: most of the PDF's are not showing

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#40]
After migrating from V4 to V5, I have an issue with PDF's not showing, only the text "No PDF".

Behaviour when clicking these items differs: I sometimes get the ``E_NOTICE: Undefined index: title.``, an error which seems to be related to actual missing PDF files (that shouldn't be missing, so I need to crossreference it with my old database).

The most common behaviour is that it takes me to the PDF viewer with empty/no pages.

Based on the URL I can see the ID of the record and can confirm there is a PDF with that id (i.e. http://127.0.0.1:8080/librarian/index.php/pdf?id=571 and there is a pdf file in C:\I, Librarian\data\pdfs\000\000\000000571.pdf)

Do you have any suggestion on how to fix this?

**Comment by mkucej** [comment]
I wonder, do you have `file_hash` values populated in the `items`  SQLite table?

**Comment by mkucej** [comment]
Might be duplicate of #42

**Comment by schonhose** [comment]
Indeed a duplicate. Fix as shown for version 5.6.0 works like a charm. Thanks!
