### ISSUE TITLE
Filter or search by tags

### ISSUE THREAD

**Issue by Aktarus006** [mkucej/i-librarian-free#43]
Hello,

First I want to thank you for the good work. Your update 5.6 helped me to go from 2.1 to the actual version.

Unfortunately, I have found another bug. When I try to search or filter by tags. It doesn't work properly.

First, selecting a tag in 'Advanced Search' returns an ERROR:

![image](https://user-images.githubusercontent.com/20419262/96566448-dff27c00-12c5-11eb-82e1-2ba78482aa40.png)

500 Internal Server Error
Database error: SQLSTATE[HY000]: General error: 1 near "AND": syntax error in /var/www/librarian/classes/storage/database.php on line 226.

Second, When I try to filter by tags only the first ones are showing (we have a lot of tags). There is a link to expand at the end of the window (...
![image](https://user-images.githubusercontent.com/20419262/96566369-c5b89e00-12c5-11eb-8173-ba95e78b15ac.png)
) but this one just shuts down the window and nothing happens.

Can you help us with this?

Regards,

Joachim

**Comment by Aktarus006** [comment]
Hi,

Still not found how to solve this error/issue.
Can you tell me in which file I have to search?

Regards,

Joachim

**Comment by mkucej** [comment]
The 2.1 version is over 10 years old, I can't really help you here. You can change `error_messages` `level` to debug in the `ilibrarian.ini` file to get more information about the database error. I think you will have to open the database files themselves and look whether the tags actually got migrated at all. If you can't figure this out, you can contact the company at our support email and hire us to do a custom migration of your library.
