### ISSUE TITLE
500 Internal Server Error - Librarian\Security 

### ISSUE THREAD

**Issue by Stybyk** [mkucej/i-librarian-free#48]
Hello,
I build the l-Librarian docker image on raspberry pi - 4. 
Based on Dockerfile : https://github.com/Stybyk/docker_i-librarian/blob/master/Dockerfile

The originally prebuilt image is running on my laptop testing VM, with no problem. 

Raspberry pi - image build log (https://github.com/Stybyk/docker_i-librarian/blob/master/install.log) looks good from my own analysis.  The server´s app also looks running well, I am able to make users and upload the .pdf files, changing setup etc.
But when I try to open some pdf, it get me in error: 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qxHkgDK/servereror.jpg" alt="servereror" border="0"></a>

Why it is happening only on that armhf build. ?  Do I miss some Dependencies ?  Or is it just one platform bug?  
Please can someone propose me a solution?  What can be wrong?

**Comment by mkucej** [comment]
What is the result of
```php
var_dump(pow(2, 32))
```
on an ARM system? It should be an integer.

**Comment by Stybyk** [comment]
It´s not some normal Linux command.. 
It looks like something like php syntax ? Or where I should exactly run it ? 

bdw :  container system infromations are:  
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```

**Comment by mkucej** [comment]
Yes, it's PHP. You should be able to run it in the Terminal like this:
```sh
php -r "var_dump(pow(2,32));"
```

**Comment by Stybyk** [comment]
So, there is the float.

# php -r "var_dump(pow(2,32));"
float(4294967296)

**Comment by Stybyk** [comment]
Sorry for, late reply, I had to AFK..

I have no some good editor in that docker so I made it intuitively:


``
    public function id($value): void {

        $this->num($value);
        $this->intRange($value, 1,(int)pow(2, 32));
    }
``    

Now I get this info message when I try to open the file.  (still, nothing opened) 

Info
Provided number is out of valid range.

**Comment by mkucej** [comment]
OK, this problem seems to be connected to how your system/and or PHP works with integers. It is beyond just a simple fix, sorry.

**Comment by Stybyk** [comment]
Yes, it is strange, I never met this problem before.   If you want some quick tests, we can make some discord channel for it...  But of course, if you have time and mood for it.

**Comment by Stybyk** [comment]
Hi, again please can you shortly explain to me what is the purpose of the (int)pow(2, 32)) ? why it is directly to this number ? 
As error message said that provided number is out of the range.. I tried to decrease this to 2^20..  and now it works. 

Can I have some another issue caused by decreasing of this number ?

**Comment by Stybyk** [comment]
Finally, it works up to 2^30 !! so u guess that I get enough high number.. for whatever purpose this function have..

**Comment by mkucej** [comment]
You can lower the integer, no problem. It is a security measure that limits the max number that the software will accept from user input.

**Comment by mkucej** [comment]
Is your system 32-bit by any chance? If yes, the max integer is signed 2^31. I guess we can support 32-bit systems.

**Comment by Stybyk** [comment]
Hi, yes Raspberry-pi OS is 32 bit.
