### ISSUE TITLE
Error in exporting library to bibtex

### ISSUE THREAD

**Issue by gapost** [mkucej/i-librarian-free#51]
Hi,

I want to export my library to a bibtex file. I go to library view, press "export" and select "bibtex" and "download file" and I get the following error: 

Database error: SQLSTATE[HY000]: General error: 1 too many SQL variables.

My library has currently 1211 items and my configuration: I,Librarian 5.7.1, PHP 7.3.25, SQLite 3.29.0

**Comment by mkucej** [comment]
Thank you for your report. This message might be caused by a limit of 999 variables in SQLite. I will need to see the full error message to track the cause, because I can't reproduce this with even much higher number of items.

**Comment by gapost** [comment]
Hi, thank you for your reply.

Where can I find the full error message?

**Comment by mkucej** [comment]
**Background**

https://www.sqlite.org/limits.html

> To prevent excessive memory allocations, the maximum value of a host parameter number is SQLITE_MAX_VARIABLE_NUMBER, which defaults to 999 for SQLite versions prior to 3.32.0 (2020-05-22) or 32766 for SQLite versions after 3.32.0.

Bug went unnoticed, because the Ubuntu compiled Sqlite3 overrides the default SQLITE_MAX_VARIABLE_NUMBER to 250,000.

**Bugged code**

The issue is caused by
```PHP
\LibrarianApp\ItemsModel::itemData()
```
```PHP
// Item placeholder.
$item_placeholders = array_fill(0, count($item_ids), '?');
$item_placeholder  = join(',', $item_placeholders);
```
When the number of `$item_ids` exceeds SQLITE_MAX_VARIABLE_NUMBER, script throws error: `SQLSTATE[HY000]: General error: 1 too many SQL variables`.

Similar issue can be found in:
```PHP
\LibrarianApp\TagsModel::_getItemTags()
```
```PHP
// List of recommended tags.
$columns = str_word_count($abstract, 1);
$placeholder_arr = array_fill(0, count($columns), '?');
$placeholders = join(',', $placeholder_arr);
```

**Comment by gapost** [comment]
Hi there, 
thank you very much for your quick response to debug this issue!
George
