### ISSUE TITLE
Access exports without login or with a token

### ISSUE THREAD

**Issue by SoulEater45** [mkucej/i-librarian-free#55]
Is it possible to export the bibtex of project in the browser and make it accessable without being loged in?
I am asking, since I am using overleaf for writing my latex code and I found out, I can link files with an URL. So whenever the bibxtex updates, I do not need to make a new export and then copy paste it, but just refresh the file and it will automatically fetch the version from my self hosted I, Librarian. This could also be realisable with a token which is inserted in the query of the URL (security wise it should't be a problem, since headers and queries are encrypted with by HTTPS).

**Comment by mkucej** [comment]
Sorry, this is unlikely to be added. We are working for a proper API with OAuth2, but it won't be included in the free version.
