### ISSUE TITLE
PDF viewer and PHP8

### ISSUE THREAD

**Issue by luis-j** [mkucej/i-librarian-free#56]
Hi, when using I, Librarian internal PDF viewer, I can't select text, and if I try to make annotations, the following error appears:

500 Internal Server Error
E_DEPRECATED: Function libxml_disable_entity_loader() is deprecated.

I have no idea of the internals of I, Librarian, but searching for the error, I found this:

Warning: This function has been DEPRECATED as of PHP 8.0.0. Relying on this function is highly discouraged.

(https://www.php.net/manual/en/function.libxml-disable-entity-loader.php)

**Comment by mkucej** [comment]
Thank you for reporting this. We did not switch to PHP 8 yet. This issue will be fixed in the next version.

**Comment by luisjure** [comment]
Hi, I downloaded and installed the new 5.9.0 release. I'd like to report that the error message disappeared, but now I'm afraid the PDF viewer doesn't work at all, and shows all blank pages. I attach a screenshot.

![I,Librarian](https://user-images.githubusercontent.com/17416997/119048916-46439800-b996-11eb-88d7-f3206b8b29aa.png)

**Comment by mkucej** [comment]
Thank you for your report. This issue has been closed. Please create a new one, if your problem persists.

1. Is everything green in `Administrator` > `Software details`?
2. When you open your browser Network console, do you see any errors returned for the page requests?

**Comment by luisjure** [comment]
I solved the problem, some PHP extensions were not enabled in my php.ini, sorry for the noise and thank you for your help.
