### ISSUE TITLE
Error 500 when exporting

### ISSUE THREAD

**Issue by luisjure** [mkucej/i-librarian-free#58]
Hi, I'm using I, Librarian on Arch Linux (currently 5.9.1 with PHP 8.0.7), and offline export is not working for me, I get this error:

Oops!
Call to undefined function Librarian\Http\Client\json_encode().

I don't know if it's a bug in I, Librarian, or something wrong in my installation. On Software details, everything is green.

Thanks for your attention.

**Comment by mkucej** [comment]
Thank you for reporting this. It will be fixed in the next version.

**Comment by luisjure** [comment]
That's wonderful, thank you.

A related question: I intend to format my HD to reinstall a Linux distribution anew. Is it viable to simply compress the whole librarian directory under www and then uncompress it in the new system? Will that work?

**Comment by mkucej** [comment]
Yes. All new files are stored in `data` directory, which must be writable by web server. You should include `data` in your daily backups.
