### ISSUE TITLE
Backup i-librarian data and config

### ISSUE THREAD

**Issue by michaelsage** [mkucej/i-librarian-free#64]
Am I right in thinking that to backup i-librarian I need to backup the /var/lib/i-librarian/data directory (the PDF location) and the /usr/share/i-librarian/ (database and webshare). Is there anything else I need to take into account?

Thanks

Michael

**Comment by mkucej** [comment]
_I, Librarian_ only writes to `/var/lib/i-librarian/data`. If you changed the **ini** file in `/etc/i-librarian`, you may need to back it up too.
