### ISSUE TITLE
PHP warnings related to "JIT memory"

### ISSUE THREAD

**Issue by gapost** [mkucej/i-librarian-free#65]
I am getting frequently the following warning:

***********************************
Warning: preg_replace_callback(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /home/www/librarian/classes/http/client/psr7/uri.php on line 705
Error: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time. Error: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time.
************************************

What would be the best solution?
(a) Changing  PHP permissions (which ones?) or (b) setting pcre.jit=0 as suggested  in the warning?

**Comment by mkucej** [comment]
This is related to your system. If you can't figure out how to allow PHP to reserve exec memory, changing the ini setting will work.
