### ISSUE TITLE
Importing BibTeX with capital letters in field names

### ISSUE THREAD

**Issue by gapost** [mkucej/i-librarian-free#66]
I noticed while importing bibtex entries from JabRef that if bibtex field names have capital letters they cannot be imported.

E.g., importing the following bibtex record

```
@Article{Akai1986,
  Title                    = {Isomer Shifts and Their Relation to Charge Transfer in Dilute Fe Alloys}, 
  Author                   = {Akai, H. and Bl\"ugel, S. and Zeller, R. and Dederichs, P. H.},
  Journal                  = {Phys. Rev. Lett.},
  Year                     = {1986},
  Pages                    = {2407--2410},
  Volume                   = {56},
  Doi                      = {10.1103/PhysRevLett.56.2407}
}
```
results in a "400 Bad Request: Item title is required".

If I change the field names to title, author, etc the record can be imported without problem.

**Comment by mkucej** [comment]
Thanks for reporting this. It will be foxed in the next version.
