### ISSUE TITLE
Annotations in PDFs

### ISSUE THREAD

**Issue by DOFfactory** [mkucej/i-librarian-free#7]
Just testing the new I, Librarian 5 and I imported a PDF with annotations and notes made in other software (Xodo PDF). I usually have good experience with these annotations across multiple software, however, in I, Librarian 5 the highlights render the colours as full fill, and not transparent. This means that whatever is highlighted in the PDF by other software, in I, Librarian the colours cover the text making them unreadable.

![image](https://user-images.githubusercontent.com/10846169/80270169-24ee7a80-86b6-11ea-8d0b-701f6f1ff323.png)

**Comment by mkucej** [comment]
We use an external library to process PDFs. This maybe a bug upstream in Poppler, or a bug in Xodo PDF. When I added annotations using _I, Librarian_, export the PDF with the annotations, and re-import it back to _I, Librarian_, no annotations are visible. This is the correct/intended behavior.

**Comment by DOFfactory** [comment]
I think there is an issue with Poppler then, as Xodo annotations show up all fine with Adobe and other PDF readers.

**Comment by mkucej** [comment]
Theoretically, if there was a way to identify the bugged highlights in the SVG, we could compensate for the bug by removing the highlights in post-processing.

**Comment by mkucej** [comment]
This bug was reported upstream in 2015 and has not been fixed yet.
https://gitlab.freedesktop.org/poppler/poppler/issues/375

**Comment by DOFfactory** [comment]
OK, thanks for having a look. This then explains why all the other "modern" PDF viewers render annotations correctly. I would love to hear your thoughts about how this can be addressed/resolved in I, Librarian. This is a deal-breaker for me, otherwise I see very little added value in using it.

**Comment by mkucej** [comment]
Thanks for trying _I, Librarian_. I am sorry that you don't see a value in it. I am sure you will find other software out there that fits your needs better.
