### ISSUE TITLE
Feedback on user experience with new UI

### ISSUE THREAD

**Issue by axel-loewe** [mkucej/i-librarian-free#70]
Hi,

First of all I want to thank you a lot for providing this awesome software!
We recently transitioned from iLibrarian4 to iLibrarian5 and I appreciate many of the improvements. One thing I liked better in the old version are a couple of points in the user interface, though. I'll just write them down here, maybe they are useful for planning future updates:
* The search result list with the links to publisher / stable link etc. showing directly on the result page was something I used a lot. Now I have to open the result to be able to access the links
* Having the search query field always accessible sped up things. Now I always have to go back to the Dashboard before being able to start a new search
* Importing PDFs was just 2 clicks (Add -> Drag & Drop file to button -> Save) in the old version. Now I first have to expand the Import menu, then click wizard, click import PDF, click on local file (drag & drop doesn't work on that button, at least in Safari) and then also have to extend Project & Tag menus if I want to tag them.
* Quick access to the menu for sorting by publication/addition date was very helpful. Now it takes more clicks
* Can one set a default external metadata provider (per user or globally)?

Side note: can projects be renamed and changed from public to private or vice versa?

Hope this feedback helps to further improve iLibrarian. Your work is much appreciated!

**Comment by mkucej** [comment]
Hi:

Thank you for the suggestions.

> The search result list with the links to publisher / stable link etc. showing directly on the result page was something I used a lot.

URL links were added to the Summary list.

> Importing PDFs was just 2 clicks

Quick import links were added to Dashboard. You can also drag and drop files on all upload forms now.

> Can one set a default external metadata provider

No, but the last selected provider is now saved in the import form.

**Comment by axel-loewe** [comment]
Thanks a lot, very useful improvements!
