### ISSUE TITLE
Error when trying to manage PDF for publications added in I, Librarian 4

### ISSUE THREAD

**Issue by MarieHouillon** [mkucej/i-librarian-free#71]
We have migrated from I, Librarian 4 to I, Librarian 5 a few months ago. This went fine in general, but it was impossible in I, Librarian 5 to replace the PDF file of a publication added in I, Librarian 4.

When clicking on Pdf > Manage PDF, an error was raised:
`gzdecode(): data error`

We could find a workaround by catching the error, raised in [app/models/pdf.php:121](https://github.com/mkucej/i-librarian-free/blob/829c8ee7d47b706a4bd2bb23cdaf923655176055/app/models/pdf.php#L121)

**Comment by mkucej** [comment]
fixed in 5.10.1
