### ISSUE TITLE
Update citation key (feature request)

### ISSUE THREAD

**Issue by luis-j** [mkucej/i-librarian-free#72]
Hi, this is a feature request.

The most common situation for me is to import files manually selecting a local PDF file. By default, the generated Citation key is something like: 

unknownunknown_SomethingFromFile

If I edit the DOI field and click Autoupdate, many fields are completed automatically (Author(s), Title, Journal, etc.). However, the citation key is not regenerated. 

If feasible, I would suggest that regenerating the citation key from the metadata would be a useful and valuable feature.

Thanks for your attention.

**Comment by mkucej** [comment]
added in 5.10.1
