### ISSUE TITLE
Text is blurry in i-librarian pdf viewer when document is opened with chromium-based browser

### ISSUE THREAD

**Issue by antibunching** [mkucej/i-librarian-free#73]
Hello all,

This application seems to suffer from a chromium related issue which makes the text blurry and uncomfortable to read. It works great on Firefox. 
Workaround on stackoverflow: 
https://stackoverflow.com/questions/37906602/blurry-downscaled-images-in-chrome

**Comment by antibunching** [comment]
The issue can be fixed by turning off hardware acceleration on the settings page.

**Comment by mkucej** [comment]
We addressed the Chrome awful image scaling in 5.9.0. What you are describing sounds like another Chrome bug. There is nothing we can do about that.

**Comment by antibunching** [comment]
Yes, it happens on all zoom levels. 
After a while I realized this problem only occurs on my laptop. On chromium on my work PC, no text blurring happens. I will post an update if I find out why in the future, but for now I am gonna just disable HW acceleration. Thanks!
