### ISSUE TITLE
Question: Configuration of LDAP server

### ISSUE THREAD

**Issue by cristobaltapia** [mkucej/i-librarian-free#85]
Hi,

first of all, thanks for this nice software! I wanted to try the LDAP login to show to my colleagues at the lab, but didn't succeed. I found the file [config/ilibrarian-default.ini](https://github.com/mkucej/i-librarian-free/blob/master/config/ilibrarian-default.ini) which I edited with the test LDAP server from [1] and copied the information to `php.ini`. (I made sure to set `ldap_active = "1"`.) That did not work for me. Is that the proper way to configure this? The program works correctly and I can login with a normal account. What am I missing?

Edit:

I am using the Dockerfile provided in [cgrima/docker](https://github.com/cgrima/docker_i-librarian).

[1] www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server

**Comment by mkucej** [comment]
Assuming their LDAP service still works, try to disable TLS: `ldap_use_tls = "0"`.
