### ISSUE TITLE
code for generating PDF text preview of fulltext search terms missing?

### ISSUE THREAD

**Issue by laf0rge** [mkucej/i-librarian-free#86]
When I use the demo instance and do a fulltext search in PDF files (e.g. for the word "encryption" in https://i-librarian.net/demo/#items/main?search_query%5B%5D=encryption&search_boolean%5B%5D=AND&search_type%5B%5D=anywhere&search_sort=relevance) I get a nice preview of the pdf fulltext with context around highlihgted search terms

![ilibrarian-hosted-search-context](https://user-images.githubusercontent.com/1250205/213105628-ad8190cf-8368-46f2-9b84-a55d135c3180.png)

I've been trying to reproduce this in a self-hosted instance that I'm considering to set up for the document archive of an open source project I run.  There, while full-text search works, the result list contains just the titles of the documents, but no [con]text below each document title.

I cannot find the code that actually generates this preview.  As far as I can tell, the function `titleList(aray $items)` in `app/views/items.php` is generating the related HTML, and it doesn't contain related code. What am I missing?  Is the demo running a branch other than master?

Thanks in advance.

**Comment by mkucej** [comment]
Self-hosted version does not have al the functionality of our commercial products. See here:
https://i-librarian.net/compare

**Comment by laf0rge** [comment]
This is rather unfortunate. I don't mind having to pay a reasonable amount for a rather important feature like this.  My main concerns is not that one would have to pay for a feature, but that paid options only exist for SaaS but not for self-hosting.  But in any case, it is of course your software and you can license it as you see fit.

**Comment by WantToLearnJapanese** [comment]
Hmm? Could you answer clearly? @mkucej I emailed months ago about self-hosting version about setting my own domain for SaaS.

I think its also could be called as self hosted version.

I doubt you may mean free version of self hosted version right?

**Comment by laf0rge** [comment]
> Hmm? Could you answer clearly? @mkucej I emailed months ago about self-hosting version about setting my own domain for SaaS.
> 
> I think its also could be called as self hosted version.

self-hosting means running software (whether it's FOSS or proprietary) on my own infrastructure.  My data doesn't leave my sphere of control, and it is my responsibilty to cere about operational aspects like reliability, upgrades, scalability, etc.  This is how folks like myself have operated their infrastructure ever since the 90s.

SaaS means all my data is leaving my sphere of control, uploaded to some other entities' infrastructure, and they operate everything as a service.  Whether or not that service operates under my own DNS domain name doesn't change the fact it is stil SaaS.

My remark was specifically regarding the fact that the question "free or pro" was mingled with the question of "self-hosted or SaaS".  So you can either have the free/FOSS version self-hosted, or you can have the pro[prietary] version as Saas, but not the pro[prietary] version in a self-hosted scenario.

**Comment by WantToLearnJapanese** [comment]
> > Hmm? Could you answer clearly? @mkucej I emailed months ago about self-hosting version about setting my own domain for SaaS.
> 
> > 
> 
> > I think its also could be called as self hosted version.
> 
> 
> 
> self-hosting means running software (whether it's FOSS or proprietary) on my own infrastructure.  My data doesn't leave my sphere of control, and it is my responsibilty to care about operational aspects like reliability, upgrades, scalability, etc.  This is how folks like myself have operated their infrastructure ever since the 90s.
> 
> 
> 
> SaaS means all my data is leaving my sphere of control, uploaded to some other entities' infrastructure, and they operate everything as a service.  Whether or not that service operates under my own DNS domain name doesn't change the fact it is stil SaaS.
> 
> 
> 
> My remark was specifically regarding the fact that the question "free or pro" was mingled with the question of "self-hosted or SaaS".  So you can either have the free/FOSS version self-hosted, or you can have the pro[prietary] version as Saas, but not the pro[prietary] version in a self-hosted scenario.
> 
> 
> 
> 

No, SaaS (Software as a Service) does not always mean that it is not self-hostable.

**Comment by mkucej** [comment]
This is what we currently offer:

1. We have two SaaS cloud products: Pro, and Lite. This is a fully hosted service.
2. We have one hybrid cloud SaaS: Pro Local Storage. This product allows you to store your data locally. We never store it, not even in a cache. Your data is just formatted, and encrypted for your browser on our app servers.
3. We sell full Pro On-Premise solution to companies. If you represent a company, please reach out for a quote.
4. We provide completely free and open source version for casual users.

We are working on a next Pro version that will be available for personal self-hosted use. This will be likely released sometimes next year.
