### ISSUE TITLE
PDF preview not shown when "display items as icons" is selected 

### ISSUE THREAD

**Issue by gapost** [mkucej/i-librarian-free#9]
Hello,

Many thanks for this update to I-Librarian.

I installed 5.1.0 and migrated my 4.10 library of 1000+ articles.

When I go to Library and select "display items as icons" only the text "PDF preview" appears in the items instead of a real preview of the pdf. I attach a screenshot:

![Screenshot from 2020-04-27 14-47-50](https://user-images.githubusercontent.com/2189002/80369761-79048500-8897-11ea-8b45-a51745239353.png)

**Comment by mkucej** [comment]
I cannot reproduce this. Most likely, the PDFs are missing in the new library's data directory.

**Comment by gapost** [comment]
No, the PDFs are there and other functions of I-Librarian work fine (e.g., open & download PDF, import new entries, etc)

Actually, the label "PDF preview" that appears instead of the actual preview is a link. When clicked it opens the PDF file.

**Comment by mkucej** [comment]
Opening one of the icon links in a new tab might give you an error message.

**Comment by gapost** [comment]
I tried to right-click on the "PDF preview" link and "Open in new tab". Again, it just opens the PDF.

The link looks like this: "https://.../.../librarian5/public/index.php/pdf?id=1217"

**Comment by mkucej** [comment]
Do you have a `View image`, `Open image`, or something similar in the right-click menu? Try that.

**Comment by gapost** [comment]
With right-click/"View image" I got the error: "Exception: PDF to image page conversion failed"

**Comment by mkucej** [comment]
You probably don't have some requirements installed. Check the Details in Administrator menu.

**Comment by gapost** [comment]
In "Administrator/Software details" it shows everything installed (green) except the ldap php extension which I do not use.

**Comment by mkucej** [comment]
There is something different on your system. The method where icon is generated:
https://github.com/mkucej/i-librarian-free/blob/master/classes/media/pdf.php#L440

**Comment by gapost** [comment]
The version of _pdftocairo_ on my system (CentOS 7) is probably outdated:

> $ pdftocairo -v
pdftocairo version 0.26.5
Copyright 2005-2014 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC

It seems it does not recognize the -jpegopt option.

**Comment by mkucej** [comment]
Oh yeah. That's definitely the reason. It should not bee too difficult to upgrade poppler-utils though.
