### ISSUE TITLE
Import folder not working

### ISSUE THREAD

**Issue by piersond** [mkucej/i-librarian-free#95]
Perhaps nothing wrong here, just a question I'm hoping you'd be so kind to answer. I'm trying to understand how the import folder works. I dropped a few PDFs in the folder, but nothing has happened after a few days. Is there a button or a setting that I'm unaware of? Also, is it possible to add another watch folder?

I'm using a Docker container to host my library. As far as I'm aware, I've made no changes to the default settings.

**Comment by mkucej** [comment]
The import folder only works with Bibtex, or RIS import. You can migrate collections (both metadata, and PDFs) in one go. *I, Librarian* is a server-based software, it cannot "watch" a folder on client machines due to security limitations.
