### ISSUE TITLE
Set local directory for library

### ISSUE THREAD

**Issue by anthonyattacks** [mkucej/i-librarian-free#97]
I'm attempting to import / use as the base library directory one that includes all of my research papers on bind-mounted storage for my I-Librarian LXC. I've installed via the .deb package on an Ubuntu 22.04 installation, set up my api keys, and attempted to modify both the ilibrarian-default.ini (a copy titled ilibrarian.ini) and the php.ini files to include the directory, so far to no avail. Modifying the former does not appear to make any chance (using key words from the now-deprecated version as well as attempting to set the path under these two flags:

**via /etc/i-librarian/config/ilibrarian-default.ini**
; Remote storage settings.
;
[remote_storage]

; If data storage is on a remote server, enter its URL here.
; Not implemented.
remote_url = "/mnt/research"

**and via php.ini:**
open_basedir = /mnt/research

I have searched around a bit and, while the above is referenced in the deprecated version, I can't seem to find any documentation on it on this version. Anyone aware of the solution, or of a gui setting I'm missing? I can import the folder, but that seems like it makes a local copy which would increase the overhead of the lxc and create redundant versions that would complicate management. Some way of setting the base library directory would be ideal. Note that using the URL for the directory itself as Samba broadcasts it isn't possible, as the network share is password protected.

**Comment by mkucej** [comment]
You can import papers using the web interface. The `import` folder is just to add PDFs together with Bibtex/RIS/Endnote XML metadata.

**Comment by anthonyattacks** [comment]
As I mentioned, that makes a second local copy. I already have the papers on a shared directory, and I have several gigabytes of papers as a working scientist. Being able to set the directory would be much more useful, as was the case in the deprecated version. Thank you for taking the time to respond, although this did not address or solve the issue.
